// laravel_12_projects/laravel_12_CRUD_inertia_vuejs_shadcnvue_with_fileupload/resources/js/pages/posts/Edit.vue
<script setup lang="ts">
import AppLayout from '@/layouts/AppLayout.vue';
import { type BreadcrumbItem } from '@/types';
import { Textarea } from '@/components/ui/textarea'
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import InputError from '@/components/InputError.vue';
import { Head, useForm} from '@inertiajs/vue3';
import {ref} from 'vue';

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Edit Post',
        href: '/posts',
    },
];

const {currentPost} = defineProps<{
    currentPost:Post
}>();

const form = useForm<PostForm>({
    title: currentPost.title,
    content: currentPost.content,
    image: null,
    _method: 'put',
});

const imagePreview = ref<string | null>(null);

const submit = () => {
    form.post(route('posts.update', currentPost.id));
};

const handleImageInput = (e:Event) => {
    const target = e.target as HTMLInputElement;
    const file = target.files?.[0];
        if(file){
            form.image = file;
            imagePreview.value = URL.createObjectURL(file);
        }
};

</script>

<template>
    <Head title="Update Post" />

    <AppLayout :breadcrumbs="breadcrumbs">
        <div class="flex h-full flex-1 flex-col gap-4 rounded-xl p-4">

            <div class="min-w-md mx-auto p-6 mt-8 bg-white dark:bg-neutral-800 shadow-lg rounded-xl">
                <form @submit.prevent="submit" class="flex flex-col gap-6">
                    <div class="grid gap-6">
                        <div class="grid gap-2">
                            <Label for="title">Title</Label>
                            <Input
                                id="title"
                                type="text"
                                autofocus
                                :tabindex="1"
                                autocomplete="title"
                                v-model="form.title"
                                placeholder="First post"
                            />
                            <InputError :message="form.errors.title" />
                        </div>

                        <div class="grid gap-2">
                            <Label for="image">Image</Label>
                            <Input
                                id="image"
                                type="file"
                                :tabindex="2"
                                @change="handleImageInput"
                            />
                            <div class="flex space-x-2">
                                <img v-if="currentPost.image" :src="currentPost.image" alt="" :class="[imagePreview ? 'opacity-30':'', 'h-12 w-12 rounded object-cover']">
                            <img v-if="imagePreview" :src="imagePreview" alt="" class="h-12 w-12 rounded object-cover">
                            </div>
                            <InputError :message="form.errors.image" />
                        </div>

                        <div class="grid gap-2">
                            <Label for="content">Content</Label>
                            <Textarea
                                id="content"
                                type="text"
                                :tabindex="3"
                                autocomplete="content"
                                v-model="form.content"
                                placeholder="First post"
                            />
                            <InputError :message="form.errors.content" />
                        </div>


                        <Button type="submit" class="mt-4 w-full" :tabindex="4" :disabled="form.processing">
                            <LoaderCircle v-if="form.processing" class="h-4 w-4 animate-spin" />
                            Update
                        </Button>
                    </div>


                </form>
            </div>
        </div>
    </AppLayout>
</template>

// laravel_12_projects/laravel_12_CRUD_inertia_reactjs_shadcnui_with_fileupload/resources/js/pages/posts/edit.tsx


import AppLayout from '@/layouts/app-layout';
import { type BreadcrumbItem } from '@/types';
import { Head, router, usePage} from '@inertiajs/react';
import { Textarea } from "@/components/ui/textarea"

import InputError from '@/components/input-error';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { FormEventHandler, useState } from 'react';

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Posts Edit',
        href: '/posts',
    },
];





export default function PostEdit({currentPost}: {currentPost: Post}) {
    const [title, setTitle] = useState<'string'>(currentPost.title);
    const [content, setContent] = useState<'string'>(currentPost.content);
    const [image, setImage] = useState<File|null>(null);
    const [imagePreview, setImagePreview] = useState<string|null>(null);
    const {errors} = usePage().props;

    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if(file){
            setImage(file);
            setImagePreview(URL.createObjectURL(file));
        }
    }


    const submit: FormEventHandler = (e) => {
        e.preventDefault();
        router.post(route('posts.update', currentPost.id), {
            _method:'put',
            title,
            content,
            image,
        });

    };

    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title="Posts Edit" />
            <section className="max-w-md mx-auto p-4 bg-gray-100 dark:bg-gray-900 rounded-lg">

                <form className="flex flex-col gap-6" onSubmit={submit}>
                    <div className="grid gap-6">
                        <div className="grid gap-2">
                            <Label htmlFor="title">Title</Label>
                            <Input
                                id="title"
                                type="title"
                                value={title}
                                onChange={(e) => setTitle(e.target.value)}
                                placeholder="First Post"
                            />
                            <InputError message={errors.title} />
                        </div>

                        <div className="grid gap-2">
                            <Label htmlFor="image">Image</Label>
                            <Input
                                id="image"
                                type="file"
                                onChange={handleFileChange}
                            />
                            <div className="flex gap-2">
                                <img src={currentPost.image} alt={currentPost.image} className={'h-10 w-10 rounded-full object-cover'+(imagePreview ?'opacity-50' : '')}  />
                                {imagePreview && <img src={imagePreview} alt='Preview' className='h-10 w-10 rounded-full object-cover'  />}
                            </div>
                            <InputError message={errors.image} />
                        </div>

                        <div className="grid gap-2">
                            <Label htmlFor="content">Content</Label>
                            <Textarea
                                id="content"
                                value={content}
                                onChange={(e) => setContent(e.target.value)}
                                placeholder="First Post"
                            />
                            <InputError message={errors.content} />
                        </div>



                        <Button type="submit" className="mt-4 w-full" tabIndex={4} >
                            {/* {processing && <LoaderCircle className="h-4 w-4 animate-spin" />} */}
                            Update
                        </Button>
                    </div>


                </form>

            </section>
        </AppLayout>
    );
}
