// laravel_12_projects/laravel_12_CRUD_inertia_vuejs_shadcnvue_with_fileupload/resources/js/pages/posts/Index.vue
<script setup lang="ts">

import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { toast } from 'vue-sonner';
import AppLayout from '@/layouts/AppLayout.vue';
import { type BreadcrumbItem } from '@/types';
import { Head,Link,usePage } from '@inertiajs/vue3';
import {onMounted, watch} from 'vue';

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Posts',
        href: '/posts',
    },
];


defineProps<{posts: Post[]}>();

interface Flash{
    success?: null;
    error?: null;
}

onMounted(() => {
    watch(() => usePage<{flash: Flash}>().props.flash,
    (flash: Flash) => {
        if(flash.success) {
            toast.success(flash.success);
            flash.success = null;
        }
    },{immediate:true});
})

</script>

<template>
    <Head title="Posts" />

    <AppLayout :breadcrumbs="breadcrumbs">
        <div class="flex h-full flex-1 flex-col gap-4 rounded-xl p-4">
            <div class="flex justify-end">
                <Link href="/posts/create" class="text-indigo-500 hover:text-indigo-900">Create Post</Link>
            </div>
            <div class="relative min-h-[100vh] flex-1 rounded-xl border border-sidebar-border/70 dark:border-sidebar-border md:min-h-min">
                <Table>
                    <TableCaption>A list of your recent posts.</TableCaption>
                    <TableHeader>
                        <TableRow>
                            <TableHead class="w-[100px]">
                            ID
                            </TableHead>
                            <TableHead>Title</TableHead>
                            <TableHead>Image</TableHead>
                            <TableHead class="text-right">
                            Actions
                            </TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        <TableRow v-for="post in posts" :key="post.id">
                            <TableCell class="font-medium">
                            {{ post.id }}
                            </TableCell>
                            <TableCell>{{ post.title }}</TableCell>
                            <TableCell>
                                <img src="post.image" alt="" class="h-12 w-12 rounded object-cover ">
                            </TableCell>
                            <TableCell class="flex justify-end gap-2">
                                <Link :href="route('posts.edit', post.id)" class="text-indigo-500 hover:text-indigo-600">Edit</Link>
                                <Link :href="route('posts.destroy', post.id)" method="delete" as="button" class="text-red-500 hover:text-red-600">Delete</Link>
                            </TableCell>
                        </TableRow>
                    </TableBody>
                </Table>
            </div>
        </div>
    </AppLayout>
</template>

// laravel_12_projects/laravel_12_CRUD_inertia_reactjs_shadcnui_with_fileupload/resources/js/pages/posts/index.tsx
import {
    Table,
    TableBody,
    TableCaption,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
  } from "@/components/ui/table"

import AppLayout from '@/layouts/app-layout';
import { type BreadcrumbItem } from '@/types';
import { Head, Link, usePage } from '@inertiajs/react';
import { useEffect } from "react";
import { toast } from "sonner";


const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Posts',
        href: '/posts',
    },
];

interface Post{

    id:number,
    title:string,
    content:string,
    image:string,
}

interface Flash{
    success?: string;
    danger?: string;
}

export default function PostIndex({posts} : {posts:Post[]}) {
    const {flash} = usePage<{flash : Flash}>().props;

    useEffect(()=>{
        if(flash.success){
            toast.success(flash.success)
        }
    },[flash.success])

    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title="Posts" />
            <div className="flex h-full flex-1 flex-col gap-4 rounded-xl p-4">
                <div className="flex justify-end">
                    <Link href={route('posts.create')} className="text-indigo-500 underline">Create Post</Link>
                </div>
                <div className="border-sidebar-border/70 dark:border-sidebar-border relative min-h-[100vh] flex-1 overflow-hidden rounded-xl border md:min-h-min">
                <Table>
                    <TableCaption>A list of your recent post.</TableCaption>
                        <TableHeader>
                            <TableRow>
                            <TableHead className="w-[100px]">ID</TableHead>
                            <TableHead>title</TableHead>
                            <TableHead>Image</TableHead>
                            <TableHead className="text-right">Action</TableHead>
                            </TableRow>
                        </TableHeader>
                        <TableBody>
                            {posts.map((post)=>(
                                <TableRow key={post.id}>
                                    <TableCell className="font-medium">{post.id}</TableCell>
                                    <TableCell>{post.title}</TableCell>
                                    <TableCell>
                                        <img src="{post.image}" alt="{post.image}" className="h-10 w-10 rounded-full object-cover"/>
                                    </TableCell>
                                    <TableCell className="text-right">
                                        <Link href={route('posts.edit', post.id)} className="text-indigo-500 hover:text-indigo-600 underline">Edit</Link>
                                        <Link href={route('posts.destroy', post.id)} method="delete" as="button"  className=" ml-2 text-red-500 hover:text-red-600 underline">Delete</Link>
                                    </TableCell>
                                </TableRow>
                            ))}
                        </TableBody>
                </Table>

                </div>
            </div>
        </AppLayout>
    );
}
