// laravel_12_projects/laravel_12_CRUD_inertia_reactjs_shadcnui_with_fileupload/resources/js/pages/posts/create.tsx


import AppLayout from '@/layouts/app-layout';
import { type BreadcrumbItem } from '@/types';
import { Head, useForm} from '@inertiajs/react';
import { Textarea } from "@/components/ui/textarea"

import InputError from '@/components/input-error';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { FormEventHandler, useState } from 'react';

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Posts Create',
        href: '/posts/create',
    },
];

type PostForm = {
    title: string;
    content: string;
    image: File|null;
};



export default function PostCreate() {
     const [imagePreview, setImagePreview] = useState<string|null>(null);
     const { data, setData, post, processing, errors} = useForm<Required<PostForm>>({
        title: '',
        content: '',
        image: null,
    });

    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if(file){
            setData('image',file);
            setImagePreview(URL.createObjectURL(file));
        }
    }


    const submit: FormEventHandler = (e) => {
        e.preventDefault();
        post(route('posts.store'));
    };

    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title="Posts Create" />
            <section className="max-w-md mx-auto p-4 bg-gray-100 dark:bg-gray-900 rounded-lg">

                <form className="flex flex-col gap-6" onSubmit={submit}>
                    <div className="grid gap-6">
                        <div className="grid gap-2">
                            <Label htmlFor="title">Title</Label>
                            <Input
                                id="title"
                                type="title"
                                value={data.title}
                                onChange={(e) => setData('title', e.target.value)}
                                placeholder="First Post"
                            />
                            <InputError message={errors.title} />
                        </div>

                        <div className="grid gap-2">
                            <Label htmlFor="image">Image</Label>
                            <Input
                                id="image"
                                type="file"
                                onChange={handleFileChange}
                            />
                            {imagePreview && <img src={imagePreview} alt='Preview' className='h-10 w-10 rounded-full object-cover'  />}
                            <InputError message={errors.image} />
                        </div>

                        <div className="grid gap-2">
                            <Label htmlFor="content">Content</Label>
                            <Textarea
                                id="content"
                                value={data.content}
                                onChange={(e) => setData('content', e.target.value)}
                                placeholder="First Post"
                            />
                            <InputError message={errors.content} />
                        </div>



                        <Button type="submit" className="mt-4 w-full" tabIndex={4} disabled={processing}>
                            {/* {processing && <LoaderCircle className="h-4 w-4 animate-spin" />} */}
                            Store
                        </Button>
                    </div>


                </form>

            </section>
        </AppLayout>
    );
}

// laravel_12_projects/laravel_12_CRUD_inertia_vuejs_shadcnvue_with_fileupload/resources/js/pages/posts/Create.vue
<script setup lang="ts">
import AppLayout from '@/layouts/AppLayout.vue';
import { type BreadcrumbItem } from '@/types';
import { Textarea } from '@/components/ui/textarea'
import InputError from '@/components/InputError.vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Head, useForm} from '@inertiajs/vue3';
import {ref} from 'vue';

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Create Post',
        href: '/posts',
    },
];

const form = useForm<PostForm>({
    title: '',
    content: '',
    image: null,
});

const imagePreview = ref<string | null>(null);

const submit = () => {
    form.post(route('posts.store'));
};

const handleImageInput = (e:Event) => {
    const target = e.target as HTMLInputElement;
    const file = target.files?.[0];
        if(file){
            form.image = file;
            imagePreview.value = URL.createObjectURL(file);
        }
};

</script>

<template>
    <Head title="create Post" />

    <AppLayout :breadcrumbs="breadcrumbs">
        <div class="flex h-full flex-1 flex-col gap-4 rounded-xl p-4">

            <div class="min-w-md mx-auto p-6 mt-8 bg-white dark:bg-neutral-800 shadow-lg rounded-xl">
                <form @submit.prevent="submit" class="flex flex-col gap-6">
                    <div class="grid gap-6">
                        <div class="grid gap-2">
                            <Label for="title">Title</Label>
                            <Input
                                id="title"
                                type="text"
                                autofocus
                                :tabindex="1"
                                autocomplete="title"
                                v-model="form.title"
                                placeholder="First post"
                            />
                            <InputError :message="form.errors.title" />
                        </div>

                        <div class="grid gap-2">
                            <Label for="image">Image</Label>
                            <Input
                                id="image"
                                type="file"
                                :tabindex="2"
                                @change="handleImageInput"
                            />
                            <img v-if="imagePreview" :src="imagePreview" alt="" class="h-12 w-12 rounded object-cover">
                            <InputError :message="form.errors.image" />
                        </div>

                        <div class="grid gap-2">
                            <Label for="content">Content</Label>
                            <Textarea
                                id="content"
                                type="text"
                                :tabindex="3"
                                autocomplete="content"
                                v-model="form.content"
                                placeholder="First post"
                            />
                            <InputError :message="form.errors.content" />
                        </div>


                        <Button type="submit" class="mt-4 w-full" :tabindex="4" :disabled="form.processing">
                            <LoaderCircle v-if="form.processing" class="h-4 w-4 animate-spin" />
                            Create
                        </Button>
                    </div>


                </form>
            </div>
        </div>
    </AppLayout>
</template>
